// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "76c19152-4d56-4be1-9841-82732d4913d5";

const char SSID[]               = "Your Key";    // Network SSID (name)
const char PASS[]               = "Your Key";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "Your Key";    // Secret device password

String acIMessenger;
float acTemperature;
float acHumidity;
float acPressure;
float acDPressure;
CloudTemperatureSensor acCtemperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(acIMessenger, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(acTemperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(acHumidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(acPressure, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(acCtemperature, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);